refactor(github_workflow): command -v checks

diff --git a/scripts/github_workflow b/scripts/github_workflow
--- a/scripts/github_workflow
+++ b/scripts/github_workflow
@@ -4,6 +4,15 @@ set -euo pipefail
 
 # BEGIN HELPERS
 
+verify_commands() {
+  for cmd in "$@"; do
+    if ! command -v "$cmd" &>/dev/null; then
+      echo "'$cmd' CLI not found in PATH." >&2
+      exit 1
+    fi
+  done
+}
+
 function check_git_repo() {
   if ! git rev-parse --is-inside-work-tree &>/dev/null; then
     echo "Not inside a git repository." >&2
@@ -14,13 +23,6 @@ function check_git_repo() {
 function check_github_remote() {
   if ! git remote -v | grep -q "github.com"; then
     echo "No remote with 'github.com' found." >&2
-    exit 1
-  fi
-}
-
-function check_gh_cli() {
-  if ! command -v gh &>/dev/null; then
-    echo "'gh' CLI not found in PATH." >&2
     exit 1
   fi
 }
@@ -132,18 +134,7 @@ function wf_prepare_release() {
 - Finally, rerun the script from this release- branch and choose '🚀 Release!'
 "
   if [[ -f Cargo.toml ]]; then
-    if ! command -v cargo &>/dev/null; then
-      echo "'cargo' CLI not found in PATH." >&2
-      exit 1
-    fi
-    if ! command -v cargo-semver-checks &>/dev/null; then
-      echo "'cargo-semver-checks' CLI not found in PATH." >&2
-      exit 1
-    fi
-    if ! command -v release-plz &>/dev/null; then
-      echo "'release-plz' CLI not found in PATH." >&2
-      exit 1
-    fi
+    verify_commands cargo cargo-semver-checks release-plz
 
     test "$(git status --porcelain)" = "" || {
       echo "Dirty tree detected. Aborting."
@@ -167,10 +158,7 @@ function wf_release() {
   gh pr create --assignee @me --fill
   gh pr merge --merge --delete-branch
   if [[ -f Cargo.toml ]]; then
-    if ! command -v cargo &>/dev/null; then
-      echo "'cargo' CLI not found in PATH." >&2
-      exit 1
-    fi
+    verify_commands cargo
 
     test "$(git status --porcelain)" = "" || {
       echo "Dirty tree detected. Aborting."
@@ -222,7 +210,7 @@ function select_workflow() {
 main() {
   check_git_repo
   check_github_remote
-  check_gh_cli
+  verify_commands gh git
   check_gh_auth
 
   branch=$(get_current_branch)
