feat(github_workflow): is_clean_repo

diff --git a/scripts/github_workflow b/scripts/github_workflow
--- a/scripts/github_workflow
+++ b/scripts/github_workflow
@@ -13,11 +13,18 @@ verify_commands() {
   done
 }
 
-function check_git_repo() {
+function check_is_git_repo() {
   if ! git rev-parse --is-inside-work-tree &>/dev/null; then
     echo "Not inside a git repository." >&2
     exit 1
   fi
+}
+
+function check_is_clean_repo() {
+  test "$(git status --porcelain)" = "" || {
+    echo "Dirty tree detected. Aborting."
+    exit 1
+  }
 }
 
 function check_github_remote() {
@@ -135,15 +142,8 @@ function wf_prepare_release() {
 "
   if [[ -f Cargo.toml ]]; then
     verify_commands cargo cargo-semver-checks release-plz
-
-    test "$(git status --porcelain)" = "" || {
-      echo "Dirty tree detected. Aborting."
-      exit 1
-    }
-
     echo "Running release-plz, this might take a while..."
     release-plz update
-
     new_version=$(cargo read-manifest | jq -r .version)
     git checkout -b "release-$new_version"
   fi
@@ -159,12 +159,6 @@ function wf_release() {
   gh pr merge --merge --delete-branch
   if [[ -f Cargo.toml ]]; then
     verify_commands cargo
-
-    test "$(git status --porcelain)" = "" || {
-      echo "Dirty tree detected. Aborting."
-      exit 1
-    }
-
     new_version=$(cargo read-manifest | jq -r .version)
     git tag -a "v$new_version" -m "Release v$new_version"
     git push origin "v$new_version"
@@ -208,9 +202,10 @@ function select_workflow() {
 }
 
 main() {
-  check_git_repo
-  check_github_remote
   verify_commands gh git
+  check_is_git_repo
+  check_is_clean_repo
+  check_github_remote
   check_gh_auth
 
   branch=$(get_current_branch)
